INSERT INTO FEES (FEE_ID, NAME) VALUES (1, 'FEE 1');
INSERT INTO FEES (FEE_ID, NAME) VALUES (2, 'FEE 2');
INSERT INTO FEES (FEE_ID, NAME) VALUES (3, 'FEE 3');
INSERT INTO FEES (FEE_ID, NAME) VALUES (4, 'FEE 4');